const apartments = [
    {
        id: 1,
        title: 'My cool apartment',
        description: 'My apartment description',
        cityId: 2,
        owner: 1,
        price: 30,
        main_image: "images/apartmentsData/apartment_22.jpg",
        images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_5.jpg"],
        number_of_beds: 3,
        number_of_rooms: 4,
        address: '330 3rd Ave',
        sqft: 7500,
        status: 2,
        for_rent: false,for_sale: true},
    {id: 2, title: 'My nice apartment', description: 'My nice apartment description', cityId: 6, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: '330 3rd Ave', main_image: "images/apartmentsData/apartment_23.jpg", images: ["images/apartmentsData/apartment_6.png", "images/apartmentsData/apartment_7.jpg", "images/apartmentsData/apartment_8.jpg", "images/apartmentsData/apartment_9.jpg", "images/apartmentsData/apartment_1.jpg"], for_rent: false, for_sale: false},
    {id: 3, title: 'My cool apartment', description: 'My apartment description', cityId: 17, owner: 1, price: 40, main_image: "images/apartmentsData/apartment_25.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_1.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true,for_sale: false},
    {id: 4, title: 'My nice apartment', description: 'My nice apartment description', cityId: 13, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Saloona 23 st', main_image: "images/apartment/user-85-main.jpg", images: "images/apartment/user-85-1.jpg,images/apartment/user-85-2.jpg,images/apartment/user-85-3.jpg,images/apartment/user-85-4.jpg,images/apartment/user-85-5.jpg", for_rent: false, for_sale: true},
    {id: 5, title: 'My cool apartment', description: 'My apartment description', cityId: 4, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_25.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Rozeni 423 st', sqft: 7500, status: 2, for_rent: false,for_sale: false},
    {id: 6, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 4, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Zurik 52 st', main_image: "images/apartmentsData/apartment_26.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: true, for_sale: true},
    {id: 7, title: 'My cool apartment', description: 'My apartment description', cityId: 15, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_27.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Korab 41 st', sqft: 7500, status: 2, for_rent: false,for_sale: true},
    {id: 8, title: 'My nice apartment', description: 'My nice apartment description', cityId: 21, owner: 8, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Moris 422 st 33s', main_image: "images/apartmentsData/apartment_28.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: false, for_sale: false},
    {id: 9, title: 'My cool apartment', description: 'My apartment description', cityId: 16, owner: 7, price: 30, main_image: "images/apartmentsData/apartment_29.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: false, for_sale: false},
    {id: 10, title: 'My nice apartment', description: 'My nice apartment description', cityId: 12, owner: 6, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_30.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: true, for_sale: true},
    {id: 11, title: 'My cool apartment', description: 'My apartment description', cityId: 20, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_22.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: true},
    {id: 12, title: 'My nice apartment', description: 'My nice apartment description', cityId: 7, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: false, for_sale: false},
    {id: 13, title: 'My cool apartment', description: 'My apartment description', cityId: 8, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_22.jpg", images: ['https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg', 'https://ap.rdcpix.com/1759188762/861b901071ac8c0bbb7d4ee13c9296a3l-m0xd-w1020_h770_q80.jpg'], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 14, title: 'My nice apartment', description: 'My nice apartment description', cityId: 9, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 15, title: 'My cool apartment', description: 'My apartment description', cityId: 9, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 16, title: 'My nice apartment', description: 'My nice apartment description', cityId: 10, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 17, title: 'My cool apartment', description: 'My apartment description', cityId: 19, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 18, title: 'My nice apartment', description: 'My nice apartment description', cityId: 5, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], for_rent: true, for_sale: false},
    {id: 19, title: 'My cool apartment', description: 'My apartment description', cityId: 6, owner: 1, price: 30, main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_22.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_4.jpg"], number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', sqft: 7500, status: 2, for_rent: true, for_sale: false},
    {id: 20, title: 'My nice apartment', description: 'My nice apartment description', cityId: 2, owner: 2, price: 30, number_of_beds: 3, number_of_rooms: 4, address: 'Alenby 3 st', main_image: "images/apartmentsData/apartment_22.jpg", images: ["images/apartmentsData/apartment_8.jpg", "images/apartmentsData/apartment_2.jpg", "images/apartmentsData/apartment_1.jpg", "images/apartmentsData/apartment_4.jpg", "images/apartmentsData/apartment_7.jpg"], for_rent: true, for_sale: false
    }];

module.exports = {
    apartments
}